services:
  regression:
    build: .
    container_name: pytest-runner
    command: sh -c "python -m pytest tests/ --alluredir=allure-results"
    environment:
      - LOGIN=${LOGIN}
      - PASSWORD=${PASSWORD}
    volumes:
      - ./allure-results:/usr/workspace/allure-results
      - ./allure-report:/usr/workspace/allure-report